# Generated by Django 4.0.4 on 2022-06-01 00:42

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('main_picture', models.ImageField(upload_to=core.models.upload_to, verbose_name='main_picture')),
                ('main_description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('buy_link', models.CharField(max_length=300)),
                ('video_link', models.CharField(blank=True, max_length=300, null=True)),
                ('second_picture', models.ImageField(blank=True, null=True, upload_to=core.models.upload_to, verbose_name='second_picture')),
                ('second_description', models.TextField(blank=True, null=True)),
                ('third_picture', models.ImageField(blank=True, null=True, upload_to=core.models.upload_to, verbose_name='third_picture')),
                ('third_description', models.TextField(blank=True, null=True)),
                ('fourth_picture', models.ImageField(blank=True, null=True, upload_to=core.models.upload_to, verbose_name='fourth_picture')),
                ('fourth_description', models.TextField(blank=True, null=True)),
                ('fifth_picture', models.ImageField(blank=True, null=True, upload_to=core.models.upload_to, verbose_name='fifth_picture')),
                ('fifth_description', models.TextField(blank=True, null=True)),
                ('sixth_picture', models.ImageField(blank=True, null=True, upload_to=core.models.upload_to, verbose_name='sixth_picture')),
                ('sixth_description', models.TextField(blank=True, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categorie')),
            ],
        ),
    ]
