# Generated by Django 4.0.4 on 2022-06-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_article_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='features',
            field=models.TextField(),
        ),
    ]
