# Generated by Django 4.0.4 on 2022-06-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_article_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='best_of_year',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='our_selection_panel',
            field=models.BooleanField(default=False),
        ),
    ]
